# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM mcr.microsoft.com/devcontainers/base:trixie@sha256:38fd33602d3eba0070282a54c2f5179dd1aa3ef02ddaf711ca77adcd698edf8e AS dev

# Note: The user vscode already exists by default in Microsofts base images
ARG USERNAME=vscode

# renovate: datasource=node-version depName=node versioning=node
ARG NODE_VERSION=24
# renovate: datasource=npm depName=corepack
ARG COREPACK_VERSION=0.35.0
# renovate: datasource=npm depName=playwright
ARG PLAYWRIGHT_VERSION=1.62.1
# renovate: datasource=github-releases depName=terrastruct/d2 versioning=semver extractVersion=^v(?<version>.*)$
ARG D2_VERSION=0.8.2
# renovate: datasource=github-releases depName=aquasecurity/trivy versioning=semver extractVersion=^v(?<version>.*)$
ARG TRIVY_VERSION=0.74.0

USER root
WORKDIR /app

#? Install gosu (sudo alternative for containers)
RUN apt-get update \
  && apt-get install -y --no-install-recommends gosu \
  && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - \
  && apt-get update \
  && apt-get install -y --no-install-recommends nodejs \
  && rm -rf /var/lib/apt/lists/* \
  && node --version


RUN npm install -g corepack@${COREPACK_VERSION} \
  && corepack --version \
  && corepack enable


#? Install only system dependencies (not Playwright nor Chromium browser) for Playwright Chromium
RUN npx -y playwright@${PLAYWRIGHT_VERSION} install-deps chromium


# Install D2
RUN curl -fsSL https://d2lang.com/install.sh \
  | sh -s -- \
    --method=standalone \
    --prefix=/usr/local \
    --version "${D2_VERSION}" \
  && d2 --version


# Install Trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v${TRIVY_VERSION} \
  && trivy --version


#? Input the entrypoint.sh script and set executable permissions to it
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
